# Generated by Django 6.0.5 on 2026-05-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
