# Generated by Django 6.0.5 on 2026-05-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0003_task_task_code_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
