# Generated by Django 6.0.5 on 2026-05-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0004_alter_task_task_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
