# Generated by Django 6.0.5 on 2026-05-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0002_task_is_completed'),
        ('task_admin', '0006_task_priority'),
    ]

    operations = [
    ]
