# Generated by Django 6.0.5 on 2026-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0005_alter_task_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='high', max_length=100),
            preserve_default=False,
        ),
    ]
